# Generated by Django 5.2.9 on 2025-12-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_alter_producto_descripcion_and_more'),
        ('ventas', '0003_alter_venta_options_venta_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.producto'),
        ),
    ]
